# Load packages required to define the pipeline:
library(targets)
library(tarchetypes)

# Set target options:
tar_option_set(
  memory = "transient"
  # Packages that your targets need for their tasks.
  # packages = c("seasonal")
)

# Run the R scripts in the R/ folder with your custom functions:
tar_source("R/packages.R")
# tar_source("R/01-get-FRED-data-monthly.R")
# tar_source("R/02-get-EIA-data.R")
# tar_source("R/03-get-QCEW-data.R")
tar_source("R/04-clean-data.R")
tar_source("R/05-analysis.R")
tar_source("R/06-plot-kern-stats.R")

# Parameters for plotting
golden <- 0.5*(1 + sqrt(5))
mywidth_irf <- 12
myheight_irf <- mywidth_irf / golden
mywidth <- 6.5
myheight <- mywidth / golden
mywidth_hd <- 8
myheight_hd <- mywidth_hd / golden


csub_blue <- rgb(0, 26, 112, maxColorValue = 255)
mycolor1 <- csub_blue
mycolor2 <- colorspace::qualitative_hcl(1, palette = "Dark 3")

# list all files generated by downloading and unzipping QCEW data
# note that .* is a wild card
get_qcew_files <- here("dta", "src", list.files(path = here("dta", "src"), pattern = "^[0-9]{4}.*\\.csv", recursive = TRUE))

# Counties:
#   "Kern County, California"       

block_length = 24

# === Historical Decomposition 
# Dates for historical decomposition
hd_lvl_early_start_date <- ymd("1996-12-01")
hd_lvl_early_end_date <- ymd("2009-12-01")
hd_lvl_late_start_date <- ymd("2009-12-01")
hd_lvl_late_end_date <- ymd("2024-12-01")
# Colors for counterfactual employment series
col5 <- sequential_hcl(5, palette = "Mako")
mycolor_highlight <- "deeppink"
mycolors_counterfactual_empl <- c(less_oilsupply = col5[[4]], less_aggdemand = col5[[3]], less_rpoil = col5[[2]], less_local = col5[[1]])


list(
  # Fix data files for replication ------------------------------------------
  tar_target(file_fred_monthly, here("dta", "src", "dat_01-get-FRED-data-monthly_2025-08-10.csv"), format = "file"),
  tar_target(file_oil_production, here("dta", "src", "dat_02-get-EIA-data_oil-production_2025-08-10.csv"), format = "file"),
  tar_target(file_oil_price, here("dta", "src", "dat_02-get-EIA-data_oil-price_2025-08-10.csv"), format = "file"),
  tar_target(dat_fred_monthly, read_csv(file_fred_monthly)),  
  tar_target(dat_oil_production, read_csv(file_oil_production)),
  tar_target(dat_oil_price, read_csv(file_oil_price)),
  tar_files(files_qcew, get_qcew_files),
  # 04-clean-data -----------------------------------------------------------
  tar_target(dat_recess, get_dat_recess()),
  tar_target(dat_all_qcew, clean_qcew_data(files_qcew)),
  tar_target(dat_estabs_count, get_dat_estabs_count(dat_all_qcew)),
  tar_target(dat_qtrly_wages, get_dat_qtrly_wages(dat_all_qcew)),
  tar_target(dat_empl_qcew_cps, get_dat_empl_qcew_cps(dat_all_qcew, dat_fred_monthly)),
  tar_target(dat_empl_qcew_ind, get_dat_empl_qcew_ind(dat_all_qcew, dat_empl_qcew_cps)),
  tar_target(dat_var, get_dat_var(dat_empl_qcew_cps, dat_fred_monthly, dat_oil_production, dat_oil_price)),
  tar_target(dat_supersector_kern, get_qcew_naics_supersector("Kern")),
  tar_target(dat_wage2_kern, get_dat_wage2(dat_qtrly_wages, dat_fred_monthly, my_area_title = "Kern County, California")),
  # 05-analysis -------------------------------------------------------------
  tar_target(plt_empl, plot_employment(dat_empl_qcew_cps, dat_recess)),
  tar_target(plt_supersector_kern, plot_supersector(dat_supersector_kern, ymd("2005-01-01"))),
  tar_target(plt_establishments_total, plot_establishments_total(dat_estabs_count, dat_recess)),
  tar_target(plt_establishments_ind, plot_establishments_ind(dat_estabs_count, dat_recess)),  
  tar_target(plt_dempl, plot_dempl(dat_empl_qcew_cps, dat_recess)),
  tar_target(plt_empl_ind, plot_employment_ind(dat_empl_qcew_ind, dat_recess)),
  tar_target(plt_empl_share, plot_employment_share(dat_empl_qcew_ind, dat_recess)),
  tar_target(plt_wage_share, plot_wage_share(dat_qtrly_wages, dat_recess)),
  # Structural IRFs
  # "Kern County, California"       
  tar_target(plt_kern_analysis, plot_irf("Kern County, California", dat_var, nrep = 2000, block_length = block_length)),
  # _________________________
  # Historical decompositions
  # "Kern County, California"       
  tar_target(hd_kern, compute_hd(plt_kern_analysis)),
  tar_target(plt_hd_components_kern, plot_hd(hd = hd_kern, dat_recess = dat_recess, date_start = ymd("1995-01-01"), plt_hd_linewidth = 1.0, plt_hd_linecolor = mycolor1, ylim_lo = -6, ylim_hi = 5)),
  tar_target(dat_hd_lvl_kern_early, make_hd_level(plt_analysis = plt_kern_analysis, historical_decomp = hd_kern, date_start = hd_lvl_early_start_date, date_end = hd_lvl_early_end_date)),
  tar_target(dat_hd_lvl_kern_late,  make_hd_level(plt_analysis = plt_kern_analysis, historical_decomp = hd_kern, date_start = hd_lvl_late_start_date, date_end = hd_lvl_late_end_date)),
  tar_target(plt_hd_lvl_kern_early, plot_counterfactual_empl_lvl(df = dat_hd_lvl_kern_early$dat_plt,  dat_recess = dat_recess, 
                                                                 my_ylab = "Employment", my_legend_title = "True and\ncounterfactual series", 
                                                                 mycolors = mycolors_counterfactual_empl, mycolor_highlight = mycolor_highlight,
                                                                 plt_empl_lo = 220 * 1000, plt_empl_hi = 310 * 1000, plt_y_step = 20 * 1000)),
  tar_target(plt_hd_lvl_kern_late, plot_counterfactual_empl_lvl(df = dat_hd_lvl_kern_late$dat_plt, dat_recess = dat_recess,
                                                                my_ylab = "Employment", my_legend_title = "True and\ncounterfactual series",
                                                                mycolors = mycolors_counterfactual_empl, mycolor_highlight = mycolor_highlight,
                                                                plt_empl_lo = 260 * 1000, plt_empl_hi = 370 * 1000, plt_y_step = 20 * 1000)),
  # Combine plots using patchwork using inline function
  tar_target(plt_hd_lvl_kern, (function(x, y) (x / y))(plt_hd_lvl_kern_early$plt, plt_hd_lvl_kern_late$plt)),
  tar_target(plt_hd_kern_cumulative_change_empl, plot_hd_cumulative_change_empl(plt_analysis = plt_kern_analysis, hd = hd_kern, date_start = ymd("1995-02-01"))),
  tar_target(file_plt_hd_kern_pdf, tar_fig_save(fout = here("out", "fig_plt_hd_kern_cumulative_change_empl.pdf"), plot = plt_hd_kern_cumulative_change_empl, width = mywidth, height = myheight), format = "file"),
  tar_target(file_plt_hd_kern_tex, tikzsave(filename = here("out", "fig_plt_hd_kern_cumulative_change_empl.tex"), plot = plt_hd_kern_cumulative_change_empl, width = mywidth, heigh = myheight), format = "file"),
  # _____________________
  # Second-stage analysis
  tar_target(plt_irf2_wage_kern, plot_irf2_wage_kern(dat_wage2_kern, plt_kern_analysis)),
  tar_target(plt_irf2_dempl_kern, plot_irf2_dempl(plt_kern_analysis, dat_fred_monthly, nrep = 1000)),
  tar_target(file_plt_irf2_dempl_kern_tex, tikzsave(filename = here("out", "fig_plt_irf2_dempl_kern.tex"), plot = plt_irf2_dempl_kern, width = mywidth, height = 3 * myheight)),
  # Forecast error variance decomposition
  ## Options: dempl, oilsupply, aggdemand, rpoil
  tar_target(tbl_fevd_kern_dempl, compute_fevd_kern(plt_kern_analysis, var_name = "dempl", caption_name = "employment growth", latex_suffix = "dempl")),
  tar_target(tbl_fevd_kern_oilsupply, compute_fevd_kern(plt_kern_analysis, var_name = "oilsupply", caption_name = "oil supply", latex_suffix = "oilsupply")),
  tar_target(tbl_fevd_kern_rpoil, compute_fevd_kern(plt_kern_analysis, var_name = "rpoil", caption_name = "the real price of crude oil", latex_suffix = "rpoil")),
  # Save items --------------------------------------------------------------
  # Figures
  tar_target(file_plt_empl_share_oil_kern, tikzsave(filename = here("out", "fig_plt_empl_share_oil_kern.tex"), plot = plt_empl_share$plt_kern, width = mywidth, height = myheight), format = "file"),
  tar_target(file_plt_irf_oil_block_kern, tikzsave(filename = here("out", "fig_plt_irf_oil_block_kern.tex"), plot = plt_kern_analysis$plt_oil_block, width = mywidth, height = myheight), format = "file"),
  tar_target(file_plt_irf_empl_block_kern, tikzsave(filename = here("out", "fig_plt_irf_empl_block_kern.tex"), plot = plt_kern_analysis$plt_empl_block, width = myheight, height = mywidth), format = "file"),
  tar_target(file_plt_hd_components_kern, tikzsave(filename = here("out", "fig_plt_hd_components_kern.tex"), plot = plt_hd_components_kern, width = myheight, height = mywidth), format = "file"),
  tar_target(file_plt_historical_counterfactual, tikzsave(filename = here("out", "fig_plt_historical_counterfactual.tex"), plot = plt_hd_lvl_kern, width = myheight, heigh = mywidth), format = "file"),  
  tar_target(file_plt_historical_counterfactual_kern_early, tikzsave(filename = here("out", "fig_plt_historical_counterfactual_kern_early.tex"), plot = plt_hd_lvl_kern_early$plt, width = mywidth, heigh = myheight), format = "file"),  
  tar_target(file_plt_historical_counterfactual_kern_late, tikzsave(filename = here("out", "fig_plt_historical_counterfactual_kern_late.tex"), plot = plt_hd_lvl_kern_late$plt, width = mywidth, heigh = myheight), format = "file"),  
  tar_target(file_plt_kern_analysis_tex, tikzsave(filename = here("out", "fig_plt_kern.tex"), plot = plt_kern_analysis$plt_all, width = mywidth_irf, heigh = myheight_irf), format = "file"),    
  # Tables of counterfactual employ
  tar_target(tbl_historical_counterfactual_kern_early, make_table_counterfactual_empl(dat_hd_lvl_kern_early$dat_plt, c(ymd("2000-01-01"), ymd("2005-01-01"), ymd("2009-12-01")))),
  tar_target(file_tbl_historical_counterfactual_kern_early, tbl_save(tbl_historical_counterfactual_kern_early, here("out", "tbl_counterfactual_empl_kern_early.tex")), format = "file"),
  tar_target(tbl_historical_counterfactual_kern_late, make_table_counterfactual_empl(dat_hd_lvl_kern_late$dat_plt, c(ymd("2015-01-01"), ymd("2020-01-01"), ymd("2024-12-01")))),
  tar_target(file_tbl_historical_counterfactual_kern_late, tbl_save(tbl_historical_counterfactual_kern_late, here("out", "tbl_counterfactual_empl_kern_late.tex")), format = "file"),  
  # Forecast error variance decomposition
  tar_target(file_tbl_fevd_kern_dempl, tbl_save(tbl_fevd_kern_dempl, here("out", "tbl_fevd_kern_dempl.tex")), format = "file"),
  tar_target(file_tbl_fevd_kern_oilsupply, tbl_save(tbl_fevd_kern_oilsupply, here("out", "tbl_fevd_kern_oilsupply.tex")), format = "file"),
  tar_target(file_tbl_fevd_kern_rpoil, tbl_save(tbl_fevd_kern_rpoil, here("out", "tbl_fevd_kern_rpoil.tex")), format = "file"),  
  # Second-stage regressions
  tar_target(file_plt_irf2_wage_kern_oilsupply, tikzsave(filename = here("out", "fig_plt_irf2_wage_kern_oilsupply.tex"), plot = plt_irf2_wage_kern$plt_oilsupply, width = mywidth, height = myheight), format = "file"),
  tar_target(file_plt_irf2_wage_kern_rpoil, tikzsave(filename = here("out", "fig_plt_irf2_wage_kern_rpoil.tex"), plot = plt_irf2_wage_kern$plt_rpoil, width = mywidth, height = myheight), format = "file"),  
  tar_target(file_plt_irf2_wages, tikzsave(filename = here("out", "fig_plt_irf2_wages.tex"), plot = plt_irf2_wage_kern$plt_oilsupply / plt_irf2_wage_kern$plt_rpoil + plot_layout(axis_titles = "collect"), width = mywidth, height = myheight), format = "file"),
  # 06-plot-kern-stats ------------------------------------------------------
  tar_target(plt_pcpi_ca, plot_pcpi(bea_data = here("dta", "per-capita-personal-income-by-county_2026-02-20.csv"), color_kern = csub_blue, my_binwidth = 5000)),    
  tar_target(file_plt_pcpi_ca, tikzsave(filename = here("out", "fig_plt_pcpi_ca.tex"), plot = plt_pcpi_ca$plt, width = mywidth, height = myheight), format = "file"),  
  tar_target(plt_edu_ca, plot_educational_attainment(acs_data = here("dta", "ACSDT5Y2024.B15002-2026-02-22T231022.csv"), color_kern = csub_blue, nbins = 16)),
  tar_target(file_plt_edu_ca, tikzsave(filename = here("out", "fig_plt_edu_ca.tex"), plot = plt_edu_ca, width = mywidth, height = myheight), format = "file"),    
  # Generate report of what the code produces -------------------------------
  tar_quarto(contents, "regionalOilContents.qmd")
)
